spring:
  # 데이터베이스 설정
  datasource:
    url: jdbc:mariadb://localhost:3306/stock5_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: dtuser
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

    # HikariCP 연결 풀 설정
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000

  # JPA/Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: update  # create, create-drop, update, validate, none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
    open-in-view: false

  # 개발 환경 설정
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# 로깅 설정
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.example.stock5: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Swagger/OpenAPI 설정
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: none
    default-models-expand-depth: 3
    default-model-expand-depth: 3
  show-actuator: false
  paths-to-match:
    - /api/**
  packages-to-scan: com.example.stock5

---
# 프로파일별 설정 (개발환경)
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/stock5_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: dtuser
    password: 1234

# 개발환경에서는 더 상세한 Swagger 설정
springdoc:
  swagger-ui:
    enabled: true
    display-request-duration: true
    try-it-out-enabled: true
    filter: true
    syntax-highlight:
      activated: true
    persist-authorization: true
  api-docs:
    enabled: true
  show-actuator: true

---
# 프로파일별 설정 (운영환경)
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://prod-server:3306/stock_prod_db?useSSL=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME:prod_user}
    password: ${DB_PASSWORD:prod_password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
logging:
  level:
    org.hibernate.SQL: WARN
    com.example.stock5: INFO

# 운영환경에서는 Swagger UI 비활성화 (보안상 이유)
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false